// @ts-nocheck
import { AsyncLocalStorage } from "node:async_hooks"
import os from "node:os"

/*
 * Upstream snapshot source:
 * - Repository: https://github.com/anomalyco/opencode
 * - Original path: packages/opencode/src/plugin/codex.ts
 * - Sync date: 2026-03-23
 * - Upstream commit: unknown
 *
 * Generated by scripts/sync-codex-upstream.mjs.
 * Do not edit this file directly; update the sync script and regenerate it.
 */

/* LOCAL_SHIMS_START */
type RequestInfo = Request | URL | string

type Hooks = any
type PluginInput = any
const officialCodexExportBridgeStorage = new AsyncLocalStorage<{
  fetchImpl: typeof globalThis.fetch
  version: string
}>()

const officialCodexExportBridge = {
  version: "snapshot",
  fetchImpl(request: RequestInfo | URL, init?: RequestInit) {
    return globalThis.fetch(request, init)
  },
  async run(options: { fetchImpl?: typeof globalThis.fetch; version?: string } = {}, fn: () => Promise<any>) {
    return officialCodexExportBridgeStorage.run(
      {
        fetchImpl: options.fetchImpl ?? this.fetchImpl,
        version: options.version ?? this.version,
      },
      fn,
    )
  },
}

const Installation = {
  get VERSION() {
    return officialCodexExportBridgeStorage.getStore()?.version ?? officialCodexExportBridge.version
  },
  set VERSION(value) {
    officialCodexExportBridge.version = value
  },
}

const OAUTH_DUMMY_KEY = "official-codex-oauth"

function fetch(request: RequestInfo | URL, init?: RequestInit) {
  return (officialCodexExportBridgeStorage.getStore()?.fetchImpl ?? officialCodexExportBridge.fetchImpl)(request, init)
}
/* LOCAL_SHIMS_END */

const CODEX_API_ENDPOINT = "https://chatgpt.com/backend-api/codex/responses"

export async function CodexAuthPlugin(input: PluginInput): Promise<Hooks> {
  return {
    auth: {
      provider: "openai",
      async loader(getAuth, provider) {
        const auth = await getAuth()
        if (auth.type !== "oauth") return {}

        if (provider?.models) {
          for (const model of Object.values(provider.models)) {
            model.cost = {
              input: 0,
              output: 0,
              cache: { read: 0, write: 0 },
            }
          }
        }

        return {
          apiKey: OAUTH_DUMMY_KEY,
          async fetch(requestInput: RequestInfo | URL, init?: RequestInit) {
            const currentAuth = await getAuth()
            if (currentAuth.type !== "oauth") return fetch(requestInput, init)

            const headers = new Headers(init?.headers)
            headers.delete("authorization")
            headers.delete("Authorization")
            headers.set("authorization", `Bearer ${currentAuth.access}`)

            if (currentAuth.accountId) {
              headers.set("ChatGPT-Account-Id", currentAuth.accountId)
            }

            const parsed = requestInput instanceof URL
              ? requestInput
              : new URL(typeof requestInput === "string" ? requestInput : requestInput.url)
            const url = parsed.pathname.includes("/v1/responses") || parsed.pathname.includes("/chat/completions")
              ? new URL(CODEX_API_ENDPOINT)
              : parsed

            return fetch(url, {
              ...init,
              headers,
            })
          },
        }
      },
      methods: [
        {
          label: "ChatGPT Pro/Plus (browser)",
          type: "oauth",
          authorize: async () => ({
            url: "",
            instructions: "",
            method: "auto" as const,
            callback: async () => ({ type: "failed" as const }),
          }),
        },
      ],
    },
    "chat.headers": async (input, output) => {
      if (input.model.providerID !== "openai") return
      output.headers.originator = "opencode"
      output.headers["User-Agent"] = `opencode/${Installation.VERSION} (${os.platform()} ${os.release()}; ${os.arch()})`
      output.headers.session_id = input.sessionID
    },
  }
}

/* GENERATED_EXPORT_BRIDGE_START */
export { officialCodexExportBridge }
/* GENERATED_EXPORT_BRIDGE_END */
