import test from "node:test"
import assert from "node:assert/strict"
import { execFile as execFileCallback } from "node:child_process"
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises"
import { join } from "node:path"
import { tmpdir } from "node:os"
import { fileURLToPath } from "node:url"
import { promisify } from "node:util"

const execFile = promisify(execFileCallback)
const fakeCommit = "89abcdef0123456789abcdef0123456789abcdef"
const syncScriptPath = fileURLToPath(new URL("../scripts/sync-codex-upstream.mjs", import.meta.url))

function createCodexFixtureSource() {
  return `import type { Hooks, PluginInput } from "@opencode-ai/plugin"
import { Installation } from "../installation"

const CODEX_API_ENDPOINT = "https://chatgpt.com/backend-api/codex/responses"

export async function CodexAuthPlugin(input: PluginInput): Promise<Hooks> {
  return {
    auth: {
      provider: "openai",
      async loader(getAuth, provider) {
        const auth = await getAuth()
        if (auth.type !== "oauth") return {}

        return {
          apiKey: "official-codex-oauth",
          async fetch(requestInput: RequestInfo | URL, init?: RequestInit) {
            const currentAuth = await getAuth()
            if (currentAuth.type !== "oauth") return fetch(requestInput, init)

            const headers = new Headers(init?.headers)
            headers.set("authorization", \`Bearer \${currentAuth.access}\`)
            if (currentAuth.accountId) headers.set("ChatGPT-Account-Id", currentAuth.accountId)

            const parsed = requestInput instanceof URL ? requestInput : new URL(typeof requestInput === "string" ? requestInput : requestInput.url)
            const url = parsed.pathname.includes("/v1/responses") ? new URL(CODEX_API_ENDPOINT) : parsed

            return fetch(url, {
              ...init,
              headers,
            })
          },
        }
      },
      methods: [
        { label: "ChatGPT Pro/Plus (browser)", type: "oauth", authorize: async () => ({ url: "", instructions: "", method: "auto" as const, callback: async () => ({ type: "failed" as const }) }) },
      ],
    },
    "chat.headers": async (input, output) => {
      if (input.model.providerID !== "openai") return
      output.headers.originator = "opencode"
      output.headers["User-Agent"] = \`opencode/\${Installation.VERSION}\`
      output.headers.session_id = input.sessionID
    },
  }
}
`
}

async function makeSyncFixture() {
  const dir = await mkdtemp(join(tmpdir(), "codex-sync-"))
  const source = join(dir, "codex.ts")
  const output = join(dir, "codex-plugin.snapshot.ts")
  await writeFile(source, createCodexFixtureSource(), "utf8")
  return { dir, source, output }
}

async function runSyncScript(args) {
  return execFile(process.execPath, [syncScriptPath, ...args])
}

test("codex sync script generates snapshot from fixture source", async () => {
  const fixture = await makeSyncFixture()

  try {
    await runSyncScript([
      "--source",
      fixture.source,
      "--output",
      fixture.output,
      "--upstream-commit",
      fakeCommit,
      "--sync-date",
      "2026-03-23",
    ])

    const snapshot = await readFile(fixture.output, "utf8")
    assert.match(snapshot, /Generated by scripts\/sync-codex-upstream\.mjs/)
    assert.match(snapshot, /Original path: packages\/opencode\/src\/plugin\/codex\.ts/)
    assert.match(snapshot, new RegExp(`Upstream commit: ${fakeCommit}`))
    assert.match(snapshot, /\/\* LOCAL_SHIMS_START \*\//)
    assert.match(snapshot, /export async function CodexAuthPlugin\(input: PluginInput\): Promise<Hooks>/)
    assert.match(snapshot, /\/\* GENERATED_EXPORT_BRIDGE_START \*\//)
    assert.match(snapshot, /export \{ officialCodexExportBridge \}/)
  } finally {
    await rm(fixture.dir, { recursive: true, force: true })
  }
})

test("codex sync script check mode detects snapshot drift", async () => {
  const fixture = await makeSyncFixture()

  try {
    await runSyncScript([
      "--source",
      fixture.source,
      "--output",
      fixture.output,
      "--upstream-commit",
      fakeCommit,
      "--sync-date",
      "2026-03-23",
    ])

    await writeFile(fixture.output, `${await readFile(fixture.output, "utf8")}\n// drift\n`, "utf8")

    await assert.rejects(
      runSyncScript([
        "--source",
        fixture.source,
        "--output",
        fixture.output,
        "--upstream-commit",
        fakeCommit,
        "--check",
      ]),
      (error) => {
        assert.equal(error.code, 1)
        assert.match(error.stdout, /snapshot drift detected/)
        return true
      },
    )
  } finally {
    await rm(fixture.dir, { recursive: true, force: true })
  }
})

test("package scripts expose codex snapshot sync commands", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"))

  assert.equal(
    pkg.scripts["sync:codex-snapshot"],
    "node scripts/sync-codex-upstream.mjs --output src/upstream/codex-plugin.snapshot.ts",
  )
  assert.equal(
    pkg.scripts["check:codex-sync"],
    "node scripts/sync-codex-upstream.mjs --output src/upstream/codex-plugin.snapshot.ts --check",
  )
})
